/**
 * widget.js — Parent-page scroll driver for iframe scroll widgets
 *
 * Configuration lives here in SCROLL_WIDGET_CONFIG — no changes to the iframe
 * tag are required. This is designed for CMS environments (e.g. AEM) where the
 * iframe markup is generated by a component you do not control.
 *
 * Each entry maps a CSS selector (matching the iframe element the CMS outputs)
 * to a scroll depth in pixels. The selector can use any attribute the CMS
 * already puts on the iframe — class, src pattern, title, etc.
 *
 *   selector    — CSS selector to find the iframe on the page
 *   scrollDepth — total px of scroll distance to create (drives animation range)
 *
 * This script will:
 *   1. Find each iframe by its selector
 *   2. Wrap it in a tall div that provides scroll depth on the parent page
 *   3. Make the iframe position:sticky so it stays pinned while the user scrolls
 *   4. Compute scroll progress (0→1) and send it to the iframe via postMessage
 *
 * The iframe content listens for:
 *   window.addEventListener('message', (e) => {
 *     if (e.data.type === 'scrollProgress') { ... e.data.progress ... }
 *   });
 *
 * Works same-origin and cross-origin. No CMS cooperation required.
 */

// ── CONFIGURE HERE ──────────────────────────────────────────────────────────
var SCROLL_WIDGET_CONFIG = [
    {
        // Matches the iframe by its title attribute — set by the AEM author
        // in the component dialog. Change "Rewards Test" to match your page.
        // Alternative selectors if title is not reliable:
        //   selector: 'iframe[src*="iframe-content.html"]'  // match by src filename
        //   selector: 'iframe[src*="iframe-poc-t5rd.onrender.com"]' // match by domain
        selector: 'iframe[title="Rewards Test"]',
        // Total scroll depth in px. Must match SHOWCASE_DEPTH + VIDEO_DEPTH
        // defined in the iframe's script.js (default: 1600 + 800 = 2400).
        scrollDepth: 2400,
    },
];
// ───────────────────────────────────────────────────────────────────────────
(function () {
    'use strict';

    function getHeaderOffset() {
        return (
            parseFloat(
                getComputedStyle(document.documentElement).getPropertyValue('--header-offset')
            ) || 0
        );
    }

    function initScrollWidget(iframe, scrollDepth) {

        // ── 1. Wrap the iframe in a tall div that provides scroll depth ────────
        var wrapper = document.createElement('div');
        wrapper.className = 'scroll-widget-wrapper';
        wrapper.style.cssText = 'position:relative;width:100%;height:' + scrollDepth + 'px;';

        iframe.parentNode.insertBefore(wrapper, iframe);
        wrapper.appendChild(iframe);

        // ── 2. Make the iframe position:sticky ────────────────────────────────
        // Remove AEM-injected HTML attributes that conflict with sticky layout
        iframe.removeAttribute('height');
        iframe.removeAttribute('scrolling');

        function applyIframeStyles() {
            var offset = getHeaderOffset();
            iframe.style.cssText = [
                'position:sticky',
                'top:' + offset + 'px',
                'width:100%',
                'height:calc(100vh - ' + offset + 'px)',
                'border:0',
                'display:block',
                'overflow:hidden',
            ].join(';');
        }

        applyIframeStyles();

        // ── 3. Compute progress (0→1) and postMessage on every scroll ──────────
        var rafId = 0;

        function update() {
            rafId = 0;
            var offset = getHeaderOffset();
            var stageH = window.innerHeight - offset;
            var scrollRange = Math.max(scrollDepth - stageH, 1);
            var rect = wrapper.getBoundingClientRect();

            // scrolled = how many px past the sticky pin point the user has gone
            var scrolled = offset - rect.top;
            var progress = Math.min(Math.max(scrolled / scrollRange, 0), 1);

            try {
                iframe.contentWindow.postMessage(
                    { type: 'scrollProgress', progress: progress },
                    '*'
                );
            } catch (e) {
                // contentWindow not yet available — will retry on next scroll event
            }
        }

        function requestUpdate() {
            if (!rafId) rafId = requestAnimationFrame(update);
        }

        window.addEventListener('scroll', requestUpdate, { passive: true });
        window.addEventListener('resize', function () {
            applyIframeStyles();
            requestUpdate();
        });
        iframe.addEventListener('load', requestUpdate);

        requestUpdate();
    }

    function init() {
        SCROLL_WIDGET_CONFIG.forEach(function (config) {
            document.querySelectorAll(config.selector).forEach(function (iframe) {
                initScrollWidget(iframe, config.scrollDepth);
            });
        });
    }

    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', init);
    } else {
        init();
    }
})();
